/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Praktikum3;

import java.awt.Color;
import java.awt.Font;
import java.awt.GraphicsEnvironment;

/**
 *
 * @author ASUS
 */
public class Praktikum32 extends javax.swing.JFrame {

    /**
     * Creates new form Praktikum32
     */
    public Praktikum32() {
        initComponents();
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        String huruf[] = ge.getAvailableFontFamilyNames();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbljenis = new javax.swing.JLabel();
        lblukuran = new javax.swing.JLabel();
        lblwarna = new javax.swing.JLabel();
        plhjenis = new javax.swing.JComboBox<>();
        plhwarna = new javax.swing.JComboBox<>();
        plhukuran = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jText32 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Praktikum 3_2");

        lbljenis.setText("Jenis Font");

        lblukuran.setText("Ukuran");

        lblwarna.setText("Warna");

        plhjenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arial", "Verdana", "Tahoma" }));
        plhjenis.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                plhjenisItemStateChanged(evt);
            }
        });
        plhjenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plhjenisActionPerformed(evt);
            }
        });

        plhwarna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Merah", "Biru", "Hijau" }));
        plhwarna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plhwarnaActionPerformed(evt);
            }
        });

        plhukuran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "14", "20", "25" }));
        plhukuran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plhukuranActionPerformed(evt);
            }
        });

        jText32.setColumns(20);
        jText32.setRows(5);
        jScrollPane1.setViewportView(jText32);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lbljenis)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblukuran)
                                    .addGap(25, 25, 25)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblwarna)
                                .addGap(27, 27, 27)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(plhwarna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(plhukuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(plhjenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(36, 36, 36)
                                .addComponent(lbljenis))
                            .addComponent(plhjenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(plhukuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblukuran))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(plhwarna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblwarna))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void plhwarnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plhwarnaActionPerformed
        // TODO add your handling code here:
        if(plhwarna.getSelectedItem()=="Merah")
        {
            jText32.setForeground(Color.red);
        }
        else if(plhwarna.getSelectedItem()=="Biru")
        {
            jText32.setForeground(Color.blue);
        }
        else if(plhwarna.getSelectedItem()=="Hijau")
        {
            jText32.setForeground(Color.green);
        }
    }//GEN-LAST:event_plhwarnaActionPerformed

    private void plhukuranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plhukuranActionPerformed
        if(plhukuran.getSelectedItem()=="14")
        {
            //Font huruf=new Font("",Font.PLAIN,14);
            jText32.setFont(new Font("",Font.PLAIN,14));
        }
        else if(plhukuran.getSelectedItem()=="20")
        {
            //Font huruf=new Font("",Font.PLAIN,20);
            jText32.setFont(new Font("",Font.PLAIN,20));
        }
        else if(plhukuran.getSelectedItem()=="25")
        {
            //Font huruf=new Font("",Font.PLAIN,25);
            jText32.setFont(new Font("",Font.PLAIN,25));
        }
    }//GEN-LAST:event_plhukuranActionPerformed

    private void plhjenisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_plhjenisItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_plhjenisItemStateChanged

    private void plhjenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plhjenisActionPerformed
        // TODO add your handling code here:
        if(plhjenis.getSelectedItem()=="Arial")
        {
            //Font huruf=new Font("",Font.PLAIN,14);
            jText32.setFont(new Font("Arial",Font.PLAIN,14));
        }
        else if(plhjenis.getSelectedItem()=="Verdana")
        {
            //Font huruf=new Font("",Font.PLAIN,20);
            jText32.setFont(new Font("Verdana",Font.PLAIN,14));
        }
        else if(plhjenis.getSelectedItem()=="Tahoma")
        {
            //Font huruf=new Font("",Font.PLAIN,25);
            jText32.setFont(new Font("Tahoma",Font.PLAIN,14));
        }
    }//GEN-LAST:event_plhjenisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Praktikum32.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Praktikum32.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Praktikum32.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Praktikum32.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Praktikum32().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jText32;
    private javax.swing.JLabel lbljenis;
    private javax.swing.JLabel lblukuran;
    private javax.swing.JLabel lblwarna;
    private javax.swing.JComboBox<String> plhjenis;
    private javax.swing.JComboBox<String> plhukuran;
    private javax.swing.JComboBox<String> plhwarna;
    // End of variables declaration//GEN-END:variables
}
